import { Consonant, Vowel } from '../types';
export interface RomanMapping<T> {
  roman: string;
  value: T;
  weight: number;
}
export const VOWELS: RomanMapping<Vowel>[] = [
  ['R^I', 'ruu', 1],
  ['Ruu', 'ruu', 1],
  ['R^i', 'ru', 1],
  ['Ru', 'ru', 2],
  ['aaa', 'aa', 0.7],
  ['aa', 'aa', 1],
  ['A', 'aa', 1],
  ['iii', 'ii', 0.7],
  ['ii', 'ii', 1],
  ['I', 'ii', 1],
  ['uuu', 'uu', 0.7],
  ['uu', 'uu', 1],
  ['U', 'uu', 1],
  ['eee', 'ee', 0.7],
  ['ee', 'ee', 1],
  ['E', 'ee', 1],
  ['ai', 'ai', 1],
  ['ei', 'ai', 0.65],
  ['ooo', 'oo', 0.7],
  ['oo', 'oo', 1],
  ['O', 'oo', 1],
  ['au', 'au', 1],
  ['ou', 'au', 0.65],
  ['a', 'a', 1],
  ['i', 'i', 1],
  ['u', 'u', 1],
  ['e', 'e', 1],
  ['o', 'o', 1],
].map(([roman, value, weight]) => ({
  roman: roman as string,
  value: value as Vowel,
  weight: weight as number,
}));

export const CONSONANTS: RomanMapping<Consonant>[] = [
  ['chh', 'chh', 1],
  ['tth', 'tth', 1],
  ['ddh', 'ddh', 1],
  ['kh', 'kh', 1],
  ['gh', 'gh', 1],
  ['jh', 'jh', 1],
  ['th', 'th', 1],
  ['dh', 'dh', 1],
  ['ph', 'ph', 1],
  ['bh', 'bh', 1],
  ['shh', 'shh', 1],
  ['ng', 'ng', 1],
  ['ny', 'ny', 1],
  ['Ch', 'chh', 1],
  ['Th', 'tth', 1],
  ['Dh', 'ddh', 1],
  ['tt', 'tt', 1],
  ['dd', 'dd', 1],
  ['nn', 'nn', 1],
  ['ch', 'ch', 1],
  ['sh', 'sh', 1],
  ['ll', 'll', 0.5],
  ['rr', 'rr', 1],
  ['T', 'tt', 1],
  ['D', 'dd', 1],
  ['N', 'nn', 1],
  ['L', 'll', 1],
  ['R', 'rr', 1],
  ['S', 'sh', 1],
  ['Sh', 'shh', 1],
  ['K', 'kh', 1],
  ['G', 'gh', 1],
  ['J', 'jh', 1],
  ['P', 'ph', 1],
  ['B', 'bh', 1],
  ['f', 'ph', 0.78],
  ['w', 'v', 0.78],
  ['z', 'j', 0.55],
  ['q', 'k', 0.55],
  ['x', 'k', 0.45],
  ['k', 'k', 1],
  ['g', 'g', 1],
  ['c', 'c', 0.9],
  ['j', 'j', 1],
  ['t', 't', 1],
  ['d', 'd', 1],
  ['n', 'n', 1],
  ['p', 'p', 1],
  ['b', 'b', 1],
  ['m', 'm', 1],
  ['y', 'y', 1],
  ['r', 'r', 1],
  ['l', 'l', 1],
  ['v', 'v', 1],
  ['s', 's', 1],
  ['h', 'h', 1],
].map(([roman, value, weight]) => ({
  roman: roman as string,
  value: value as Consonant,
  weight: weight as number,
}));
